### ISSUE TITLE
Symfony 2 - Assetic Javascript compression causing errors

### ISSUE THREAD

**Issue by topclaudy** [kriswallsmith/assetic#240]
I get the same trouble mentionned here: 
http://stackoverflow.com/questions/9480707/symfony-2-assetic-javascript-compression-causing-errors
Unable to run my site in production mode.

**Comment by sjagr** [comment]
+1 on this issue. Spent an hour of client time trying to figure out what caused this and finally landed here. This should be handled by assetic. Even blindly throwing in a `;` into the end of each concatenated file would fix this.

**Comment by JonyGreen3** [comment]
i find a free <a href="http://www.online-code.net/minify-js.html">online js compressor</a> service to compress your js code, so it will reduce the size of web page.

**Comment by huitiemesens** [comment]
+1 .... this is really annoying .

**Comment by SaidMarar** [comment]
+1 and we are in 2017
