### ISSUE TITLE
Image Manipulation

### ISSUE THREAD

**Issue by richardmiller-zz** [kriswallsmith/assetic#68]
It seems to me that as well as the image optimisation already possible that it would be good to be able to do other image manipulation with Assetic to get the benefits of its caching/dumping of the results. I thought I would have a play about at creating a basic filter to do this. The first issue I have run into is that I cannot see anyway to get options from the Twig template or formula into the filter, I can only see it being possible via the service definition. That though fixes it for all uses of the filter, whereas it would be useful to be able to set options such as height and width for resizing on a per image basis.

Is this already possible? If not is it something it would make sense to add or is there a good reason not to?

**Comment by renaatdemuynck** [comment]
This is kind of a late answer but I just created a library of Assetic filters for all the Imagine Image filters:
https://github.com/renaatdemuynck/assetic-imagine-filters.git
