### ISSUE TITLE
Assetic on AWS

### ISSUE THREAD

**Issue by Looted** [kriswallsmith/assetic#711]
Hi all! I'm trying to get assetic working on AWS (in dev enviorment). I created a provisioning script which performs the dump. The dump finishes correctly... except the files don't exists (confirmed by sshing into the ec2 machine). Both js and css folders are empty. Below is the log:

    2015-01-21 14:12:34,414 [DEBUG] Running command 05_update_assets
    2015-01-21 14:12:34,414 [DEBUG] Generating defaults for command 05_update_assets <<<

    2015-01-21 14:12:35,027 [DEBUG] No test for command 05_update_assets
    2015-01-21 14:12:37,870 [INFO] Command 05_update_assets succeeded
    2015-01-21 14:12:37,871 [DEBUG] Command 05_update_assets output: Dumping all dev assets.
    Debug mode is off.

    14:12:36 [file+] /var/app/current/app/../web/css/2f21d5e.css
    14:12:36 [file+] /var/app/current/app/../web/js/b21b935.js
    14:12:36 [file+] /var/app/current/app/../web/js/2031a90.js
    14:12:36 [file+] /var/app/current/app/../web/css/92da39d.css
    14:12:36 [file+] /var/app/current/app/../web/css/b5828a3.css
    14:12:37 [file+] /var/app/current/app/../web/js/31db152.js

Does anyone have experience with using assetic on Beanstalk?

EDIT 1 
I did manage to run it via ssh with sudo. Using sudo doesn't seem like a great idea though. I'm still interested if someone resolved this issue on aws.

**Comment by tonglil** [comment]
It's most likely an issue with your permissions. What user is running the provisioning script and what are the permissions of the folder they are dumped into?

**Comment by Looted** [comment]
Hi tonglil! Thanks for responding. The user running scripts is root, however assetic dump is ran by php under webapp user. I tried chowning and chmodding the folders with no effect:

    10_chown_js:
        command: chown -R webapp:webapp web/js
    11_chmod_js:
        command: chmod -R 0777 web/js
    12_chown_css:
       command: chown -R webapp:webapp web/css
    13_chmod_css:
       command: chmod -R 0777 web/css
