### ISSUE TITLE
Assetic is not aware of asset dependencies

### ISSUE THREAD

**Issue by sonu27** [kriswallsmith/assetic#715]
We are still experiencing this issue: https://github.com/kriswallsmith/assetic/issues/79

However, if we disable the asset controller, and watch the files, it does detect changes from @imports.

**Comment by kniziol** [comment]
https://github.com/kriswallsmith/assetic/issues/79#issuecomment-74942491

**Comment by stof** [comment]
https://github.com/symfony/AsseticBundle/pull/332 has been merged, fixing the caching issue in the AssetController of the bundle.
