### ISSUE TITLE
Filter the whole collection just once

### ISSUE THREAD

**Issue by fedeisas** [kriswallsmith/assetic#740]
HI there! Reading the docs I noticed that filters are `applied to the collection will cascade to each asset leaf if you iterate over it`.

When I build my app assets, this means each file gets filtered before dumping the unified version.

Some code:

```php
$manager = new AssetManager();
$manager->set(); // I load a bunch of collections with different keys for each asset group (default, vendor, etc..)

$loadAssets = [
    new AssetReference($manager, 'default')
];

$loadFilters = [];
$loadFilters[] = new UglifyJs2Filter();

$collection = new AssetCollection($loadAssets, $loadFilters);
$collection->setTargetPath('/path/to/output/filename');

$writer = new AssetWriter('/output/dir/');
$writer->writeAsset($collection);
```

When I add the UglifyJs2Filter it gets really slow. It goes from *~28ms* per collection, to around *5s* per collection.

After looking into it, I noticed `uglify-js` gets called once for each file in the collection.

Is there any way to **concatenate** every file on the collection and then **minify**? I think that way it's going to be much faster.

**Comment by fedeisas** [comment]
@kriswallsmith ping

**Comment by kriswallsmith** [comment]
see #469
