### ISSUE TITLE
TwigFormulaLoader ignores twig extends statements

### ISSUE THREAD

**Issue by sk-sparhandy** [kriswallsmith/assetic#745]
### How it is right now

**site.twig**:
```twig
{% extends 'main.twig' %}

{% block main %}
    {% stylesheet 'example1.css' filter = '?css' %}
    <link href="{{ asset_url }}" type="text/css" rel="stylesheet" />
    {% endasset %}
{% endblock %}
```

**main.twig**:
```twig
{% stylesheet 'example2.css' filter = '?css' %}
<link href="/{{ asset_url }}" type="text/css" rel="stylesheet" />
{% endasset %}
{% block main %}
Default Content
{% endblock %}
```

**site.php**:
```php
[...]
        $twigFormulaLoader = new TwigFormulaLoader($this->twigEnvironment);
        $resource          = new TwigResource($this->twigEnvironment->getLoader(), 'site.twig');
        $lazyAssetManager  = new LazyAssetManager($this->assetFactory);

        $lazyAssetManager->setLoader('twig', $twigFormulaLoader);
        $lazyAssetManager->addResource($resource, 'twig');

        $this->assetWriter->writeManagerAssets($lazyAssetManager);

        return $this->twigEnvironment->render(
            $template,
            $parameter
        );
[...]
```
`example1.css` is build as expected. `example2.css` is ignored.

### What I expected
`example1.css` and `example2.css` are build and saved to disc.

### My Proposal
My proposal is an extension of `TwigFormulaLoader.php` as follows:
**TwigFormulaLoader.php** from line 95:
```php
        } elseif($node instanceof \Twig_Node_Module)
        {
            $innerNodes = $node->getIterator()->getArrayCopy();
            if (isset($innerNodes['parent']) && $innerNodes['parent'] instanceof \Twig_Node_Expression_Constant)
            {
                /** @var \Twig_Node_Expression_Constant $expressionConstant */
                $expressionConstant = $innerNodes['parent'];
                $parentValue = $expressionConstant->getAttribute('value');
                $resultingRessource = new TwigResource($this->twig->getLoader(), $parentValue);
                $resultingFormular = $this->load($resultingRessource);
                $formulae = array_merge($formulae, $resultingFormular);

            }
        }
```

I'm quiet new to the way `Twig_Node`s work so this may not be the right way to do it. I would be very thankful for pointers to a better way to get the described feature. If there are non or if this is the right way and there is interest in this feature I will be happy to provide a pullrequest containing this code change.

**Comment by stof** [comment]
this is because ``main.twig`` is a different template as far as Twig is concerned. If you want it to be processed, you should ask for that explicitly.

Searching automatically for all referenced templates would be a bad idea IMO: you could know that only a few templates in your project are defining assets, and then restrict the list of processed templates to only those to be faster.

**Comment by sk-sparhandy** [comment]
Thx for your quick answer @stof . I'm working with a complex pre-existing twig template framework, which I want to port to a more streamlined one with help of assetic. In theory I agree with You 100%, but the described feature would allow me to achieve my goal in an iterative way in contrast to reimplementing all templates at once.

**Comment by stof** [comment]
@sk-sparhandy you could make Assetic process all your templates to find assets for now, and then optimize the list of templates later when the templates needing it are settled. Processing more files than necessary will slow down the loading of formulae, but this is a trade-off you can make (and this trade-off is precisely the reason why I don't want to introduce some magic in the loader to change the list of resources)

**Comment by sk-sparhandy** [comment]
Thx again for your quick answer @stof. I will test processing all resources at once.
