### ISSUE TITLE
Fatal error: Class 'scssc' not found in [...]/vendor/kriswallsmith/assetic/src/Assetic/Filter/ScssphpFilter.php on line 47

### ISSUE THREAD

**Issue by mmic-bjohnson** [kriswallsmith/assetic#773]
https://github.com/leafo/scssphp/tree/v0.5.0 seems to have broken this library. This looks to be the specific commit:

https://github.com/leafo/scssphp/commit/3f87f8ba1e066f0b18880488d724ddd76d7d150b

As of 16 hours ago, `composer update` causes the following entries to be removed from `autoload_classmap.php`:

```php
    //...
   'scss_formatter' => $vendorDir . '/leafo/scssphp/classmap.php',
    'scss_formatter_compressed' => $vendorDir . '/leafo/scssphp/classmap.php',
    'scss_formatter_crunched' => $vendorDir . '/leafo/scssphp/classmap.php',
    'scss_formatter_nested' => $vendorDir . '/leafo/scssphp/classmap.php',
    'scss_parser' => $vendorDir . '/leafo/scssphp/classmap.php',
    'scss_server' => $vendorDir . '/leafo/scssphp/classmap.php',
    'scssc' => $vendorDir . '/leafo/scssphp/classmap.php',
    //...
```

Consequently, reliant libraries now yield this:

```
Fatal error: Class 'scssc' not found in [...]/vendor/kriswallsmith/assetic/src/Assetic/Filter/ScssphpFilter.php on line 47
```

**Comment by stof** [comment]
Update assetic to the latest version. We already stopped using the deprecated ``scssc`` class since Assetic 1.2

**Comment by mmic-bjohnson** [comment]
Whoops, my bad! Another third-party library had pegged Assetic to `~1.1.*`. I will follow-up with that library. Apologies for wasting your time, good sir!
