### ISSUE TITLE
File ends with \u0

### ISSUE THREAD

**Issue by wesleyvicthor** [kriswallsmith/assetic#806]
Not sure why, it seems related on how assetic dump the files but every javascript I have I got this `\u0` char at the end of the file. this simples breaks as a syntax error.

**Comment by WindBridges** [comment]
Today I faced with the same problem. After researching I found that it's not an Assetic bug. Actually, problem was found in Nginx. I solved it by changing it's config like described at [serverfault.com](http://serverfault.com/a/645425). Don't forget to restart the Nginx.
