### ISSUE TITLE
file_get_contents().failed to open stream: operation failed" at vendor/kriswallsmith/buzz/lib/Buzz/Client/FileGetContents.php line 30

### ISSUE THREAD

**Issue by manojdivakaran** [kriswallsmith/assetic#815]
Hi,
 I m trying to implement CAS in symfony and after redirecting to the CAS server (which is https) and then authenticating it gives the following error
failed to open stream: operation failed" at /var/www/html/repurposing-tool/vendor/kriswallsmith/buzz/lib/Buzz/Client/FileGetContents.php line 30
I am not able to find a solution to the same in the internet as many of those are not working,
have also set verifypeer = false in parameter.yml file

**Comment by stof** [comment]
This has nothing to do with Assetic.
