### ISSUE TITLE
[Twig] Passing a string as the $source argument of Twig_Environment::tokenize() is deprecated

### ISSUE THREAD

**Issue by francoispluchino** [kriswallsmith/assetic#818]
Since version 1.27 of Twig, passing a string as the $source argument of Twig_Environment::tokenize() is deprecated. We must pass a `Twig_Source` instance instead.

Use in [TwigFormulaLoader::load()](https://github.com/kriswallsmith/assetic/blob/master/src/Assetic/Extension/Twig/TwigFormulaLoader.php#L37) at line 37.

**Comment by hvt** [comment]
There's a PR for that, see #819.

**Comment by zapashcanon** [comment]
I think this could be closed thanks to #820.

**Comment by francoispluchino** [comment]
Thanks to #820.
