### ISSUE TITLE
Create tag 1.3.3

### ISSUE THREAD

**Issue by kubawerlos** [kriswallsmith/assetic#821]
To complete https://github.com/symfony/assetic-bundle/pull/423 and solve the deprecation's notices issue we need new tag with changes from https://github.com/kriswallsmith/assetic/pull/820.

Release note might be:
- Added SassUtils for better compatibility with bootstrap 4 (and scss comments overall) https://github.com/kriswallsmith/assetic/pull/787
- Add filter for PHP Libsass implementation https://github.com/kriswallsmith/assetic/pull/752
- Fixing deprecated notices from Twig 1.27 https://github.com/kriswallsmith/assetic/issues/818

**Comment by stof** [comment]
As there are new features, this will be 1.4 though, not 1.3.3

**Comment by kubawerlos** [comment]
Can you create it?

**Comment by scottliddick** [comment]
Thank you for your work on this  @kubawerlos

**Comment by stof** [comment]
1.4.0 has been released
