### ISSUE TITLE
How to use autoprefixer with assetic

### ISSUE THREAD

**Issue by bensampaio** [kriswallsmith/assetic#834]
I am trying to include [autoprefixer](https://github.com/postcss/autoprefixer) into my build process, but I came across the problem that the autoprefixer repo no longer publishes a bin. Eventually I came across [autoprefixer-cli](https://github.com/ai/autoprefixer-cli) which provides the required bin but I would prefer not to be dependent on a repo created just for legacy code... For that reason, I would like to know if there is any better solution for this? Thank you!

**Comment by Youhan** [comment]
Have you found any solutions?

**Comment by bensampaio** [comment]
@Youhan the solution is: do not use assetic. Use webpack :)
