### ISSUE TITLE
CSS image references

### ISSUE THREAD

**Issue by jarrettj** [kriswallsmith/assetic#856]
Hi,

Good day.

How do you handle images referenced from inside a css file? 

Regards.
JJ

**Comment by stof** [comment]
Please give more details about what you mean. What do you want to handle here ?

**Comment by jarrettj** [comment]
Hi,

This might not be directly related now that I'm thinking about it. I use the widmogrod/zf2-assetic-module, based on this repo. Will post question there, thanks.

Regards.
JJ
