### ISSUE TITLE
symfony/process ~4.0 compatibility feature request

### ISSUE THREAD

**Issue by mikemunger** [kriswallsmith/assetic#877]
Hi there,

I am using assetic within a laravel 5.x app and when attempting to upgrade laravel from 5.5 to 5.6, it wants symfony/process ~4.0.

I am hoping this might be a trivial compatibility for assetic to be able to support sometime soon.

Thanks!

**Comment by timothee-pinon** [comment]
Hi,

Can you change this dependency quickly, it also blocks the update from sf3 to sf4 that require symfony/process ~4.0.

Thanks ;)

**Comment by aykutfarsak** [comment]
Is there any work on it? I can't update Laravel project to 5.6 because of assetic package dependecy about `symfony/process`.

**Comment by elchristo** [comment]
There is already an open PR --> #866

**Comment by mikemunger** [comment]
Closing due to already open pr #866, thanks for pointing that out.
