### ISSUE TITLE
Fatal error AsseticTokenParser following twig/twig update

### ISSUE THREAD

**Issue by Soviann** [kriswallsmith/assetic#888]
Hello, since this commit : https://github.com/twigphp/Twig/commit/baa70287f5b8eff6d90c5779f82088379ebf94a4#diff-93cf20cdc02735a0532878a1b724e860

There's this error :
`Fatal error: Declaration of Assetic\Extension\Twig\AsseticTokenParser::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $token) in /private/var/www/Siqual/crm-alec27/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/AsseticTokenParser.php on line 198
`

**Comment by PhilETaylor** [comment]
Yup, I just got this after a composer update :( 

Twig 2.7.* is now namespaced.

**Comment by arjanfrans** [comment]
I have the same problem after upgrading twig from 1.34 to 1.38.

**Comment by PhilETaylor** [comment]
@arjanfrans for the time being downgrade your twig in your composer.json and run another `composer update`

`"twig/twig": "2.6.*",`

**Comment by emodric** [comment]
Reported to Twig maintainers: https://github.com/twigphp/Twig/issues/2886
